# CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_50/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="fpb"
# CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_50/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="fiqa"
# CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M/peft_50/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --datasets="tfns"

# CUDA_VISIBLE_DEVICES=0 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_50/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="fpb"
# CUDA_VISIBLE_DEVICES=0 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_50/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="fiqa"
# CUDA_VISIBLE_DEVICES=0 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_50/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --datasets="tfns"

# CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_50/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="fpb"
# CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_50/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="fiqa"
# CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_50/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --datasets="tfns"

CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_50/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="fpb"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_50/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="fiqa"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-finance/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M/peft_50/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --datasets="tfns"
